services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - '4566:4566'
    volumes:
      - './localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh'
      - '/var/run/docker.sock:/var/run/docker.sock'
  postgres:
    image: postgres:17.5-alpine
    ports:
      - 6432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=default
